
viralPlaylists = [
    {'country_code':'AD','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbMxjQJh4Um8T'},
    {'country_code':'AE','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbN6kflPvZZn0'},
    {'country_code':'AR','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbJajpaXyaKll'},
    {'country_code':'AU','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbO5MSE9RdfN2'},
    {'country_code':'AT','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbKxYYIUIgn7V'},

    {'country_code':'BE','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbJx9hUtTN0Sj'},
    {'country_code':'BO','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbMTKZuy8ORFV'},
    {'country_code':'BR','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbMOkSwG072hV'},
    {'country_code':'BG','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbJcpVBLdFV7m'},

    {'country_code':'CA','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbKfIuOAZrk7G'},
    {'country_code':'CL','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbJs8e2vk15a8'},
    {'country_code':'CO','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbKrooeK9WSFF'},
    {'country_code':'CR','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbKOefHPXPMyf'},
    {'country_code':'CZ','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbMBUm3g7j4Kb'},

    {'country_code':'DK','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbMA8BIYDeMkD'},
    {'country_code':'DO','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbJWZV7aRNQck'},
    {'country_code':'EC','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbJpRQ294oZ9N'},
    {'country_code':'SV','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbLxoIml4MYkT'},
    {'country_code':'EE','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbK4KA2JSuft7'},
    {'country_code':'EG','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbJSvmuZN9Jja'},
    {'country_code':'FI','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbMBNcyQCfU4w'},
    {'country_code':'FR','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbJmRv5TqJW16'},

    {'country_code':'DE','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbNv6cjoMVCyg'},
    {'country_code':'GR','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbLOov4J0GutU'},
    {'country_code':'GT','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbNF1heNYHDnE'},
    {'country_code':'HN','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbNpKdqfZ9Upp'},
    {'country_code':'HK','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbKXd6qahcpCg'},
    {'country_code':'HU','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbLuey1EKVv9I'},

    {'country_code':'IS','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbMHnoaLVkVuk'},
    {'country_code':'IN','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbK4NvPi6Sxit'},
    {'country_code':'ID','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbKpV6RVDTWcZ'},
    {'country_code':'IE','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbLzhUVGQUCoe'},
    {'country_code':'IS','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbNGlbFNNXxgC'},
    {'country_code':'IT','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbKbvcwe5owJ1'},
    {'country_code':'JP','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbINTEnbFeb8d'},

    {'country_code':'LV','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbIUY6VUoboP4'},
    {'country_code':'LT','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbLDLOTfCtAUM'},
    {'country_code':'LU','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbJ9SRaVj0yDF'},
    {'country_code':'MY','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbLRmg3qDbY1H'},
    # {'country_code':'MT','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbMD2H5HJqmx9'},
    {'country_code':'MX','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbLuUZrygauiA'},
    
    {'country_code':'NL','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbMQaPQjt027d'},
    {'country_code':'NZ','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbJ7gPAehey5W'},
    {'country_code':'NI','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbKgCVIE0PTOD'},
    {'country_code':'NO','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbOcsE2WCaJa2'},
    {'country_code':'PA','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbMIO7B1pcKUy'},
    {'country_code':'PY','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbNxY4E5g33Gy'},
    {'country_code':'PE','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbN7gfhgaomhA'},
    {'country_code':'PH','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbJv2Mvelmc3I'},
    {'country_code':'PL','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbNGGDnE9UFTF'},
    {'country_code':'PT','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbKHoaIcElSSA'},

    {'country_code':'RO','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbNwDVyEEfWV3'},
    #{'country_code':'RU','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbNwDVyEEfWV3'},
    {'country_code':'SG','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbJVi45MafAu0'},
    {'country_code':'SA','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbMq8xkWZE6se'},

    {'country_code':'SK','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbK3Iy2zvpfp4'},
    {'country_code':'ZA','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbNaCk6h5bujZ'},
    {'country_code':'ES','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbMfVLvbaC3bj'},
    {'country_code':'SE','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbIPOivNiyjjS'},
    {'country_code':'CH','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbNjqq6Tw4Fb0'},
    {'country_code':'TW','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbMGnTCc4Vx7v'},
    {'country_code':'TH','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbMnf7ONzeQWM'},
    {'country_code':'TR','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbMIJZxwqzod6'},
    {'country_code':'GB','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbL3DLHfQeDmV'},
    {'country_code':'UA','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbLwLH0YjrtGb'},
    {'country_code':'US','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbKuaTI1Z1Afx'},
    {'country_code':'UY','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbM1qaaFAyPLz'},
    {'country_code':'VN','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbL1G1MbPav3j'}
]