
var countries = [
    {country_code:'AR',country:'Argentina'},
    {country_code:'AU',country:'Australia'},
    {country_code:'AT',country:'Austria'},
    {country_code:'BE',country:'Belgium'},
    {country_code:'BO',country:'Bolivia'},
    {country_code:'BR',country:'Brazil'},
    {country_code:'BG',country:'Bulgaria'},
    {country_code:'CA',country:'Canada'},
    {country_code:'CL',country:'Chile'},
    {country_code:'CO',country:'Columbia'},
    {country_code:'CR',country:'Costa Rica'},
    {country_code:'CZ',country:'Czechia'},
    {country_code:'DK',country:'Denmark'},
    {country_code:'DO',country:'Dominican Rep.'},
    {country_code:'EC',country:'Ecuador'},
    {country_code:'SV',country:'El Salvador'},
    {country_code:'EE',country:'Estonia'},
    {country_code:'FI',country:'Finland'},
    {country_code:'FR',country:'France'},
    {country_code:'DE',country:'Germany'},
    {country_code:'GR',country:'Greece'},
    {country_code:'GT',country:'Guatemala'},
    {country_code:'HN',country:'Honduras'},
    {country_code:'HK',country:'Hong Kong'},
    {country_code:'HU',country:'Hungary'},
    {country_code:'IS',country:'Iceland'},
    {country_code:'IN',country:'India'},
    {country_code:'ID',country:'Indonesia'},
    {country_code:'IE',country:'Ireland'},
    {country_code:'IS','uri':'spotify:user:spotifycharts:playlist:37i9dQZEVXbJ6IpvItkve3'},
    {country_code:'IT',country:'Italy'},
    {country_code:'JP',country:'Japan'},
    {country_code:'LV',country:'Latvia'},
    {country_code:'LT',country:'Lithuania'},
    {country_code:'LI',country: "Liechtenstein"},
    {country_code:'MY',country:'Malaysia'},
    // {'country_code':'MT',country:'Malta'},
    {country_code:'MX',country:'Mexico'},
    
    {country_code:'NL',country:'Netherlands'},
    {country_code:'NZ',country:'New Zealand'},
    {country_code:'NI',country:'Nicaragua'},
    {country_code:'NO',country:'Norway'},
    {country_code:'PA',country:'Panama'},
    {country_code:'PY',country:'Paraguay'},
    {country_code:'PE',country:'Peru'},
    {country_code:'PH',country:'Philipines'},
    {country_code:'PL',country:'Poland'},
    {country_code:'PT',country:'Portugal'},
    {country_code:'RO',country:'Romania'},
    {country_code:'SG',country:'Singapore'},
    {country_code:'SK',country:'Slovakia'},
    {country_code:'ZA',country:'South Africa'},
    {country_code:'ES',country:'Spain'},
    {country_code:'SE',country:'Sweden'},
    {country_code:'CH',country:'Switzerland'},
    {country_code:'TW',country:'Taiwan'},
    {country_code:'TH',country:'Thailand'},
    {country_code:'TR',country:'Turkey'},
    {country_code:'GB',country:'United Kingdom'},
    {country_code:'US',country:'United States of America'},
    {country_code:'UY',country:'Uruguay'},
    {country_code:'VN',country:'Vietnam'},
]



export default countries