const weeklyPlaylists = [
  // Asia
  { country_code: 'HK', uri: '37i9dQZEVXbMdvweCgpBAe' },
  { country_code: 'KR', uri: '37i9dQZEVXbJZGli0rRP3r' },
  { country_code: 'PH', uri: '37i9dQZEVXbJVKdmjH0pON' },
  { country_code: 'VN', uri: '37i9dQZEVXbKZyn1mKjmIl' },
  { country_code: 'JP', uri: '37i9dQZEVXbKqiTGXuCOsB' },
  { country_code: 'TW', uri: '37i9dQZEVXbMVY2FDHm6NN' },
  { country_code: 'IN', uri: '37i9dQZEVXbMWDif5SCBJq' },
  { country_code: 'ID', uri: '37i9dQZEVXbIZK8aUquyx8' },
  { country_code: 'TH', uri: '37i9dQZEVXbJ7qiJCES5cj' },
  { country_code: 'MY', uri: '37i9dQZEVXbKcS4rq3mEhp' },
  { country_code: 'SG', uri: '37i9dQZEVXbN66FupT0MuX' },

  // Middle East/Africa
  { country_code: 'TR', uri: '37i9dQZEVXbJARRcHjHcAr' },
  { country_code: 'IL', uri: '37i9dQZEVXbJ5J1TrbkAF9' },
  { country_code: 'ZA', uri: '37i9dQZEVXbJV3H3OfCN1z' },
  { country_code: 'MA', uri: '37i9dQZEVXbNM8vS9cIqAG' },
  { country_code: 'EG', uri: '37i9dQZEVXbMy2EcFg5F9m' },
  { country_code: 'SA', uri: '37i9dQZEVXbO839WGRmpu1' },
  { country_code: 'AE', uri: '37i9dQZEVXbIZQf3WEYSut' },

  // Europe
  { country_code: 'ES', uri: '37i9dQZEVXbJwoKy8qKpHG' },
  { country_code: 'IT', uri: '37i9dQZEVXbJUPkgaWZcWG' },
  { country_code: 'DE', uri: '37i9dQZEVXbK8BKKMArIyl' },
  { country_code: 'RU', uri: '37i9dQZEVXbNALwC1jxb5m' },
  { country_code: 'UK', uri: '37i9dQZEVXbMwmF30ppw50' },
  { country_code: 'SE', uri: '37i9dQZEVXbKVvfnL1Us06' },
  { country_code: 'NO', uri: '37i9dQZEVXbLWYFZ5CkSvr' },
  { country_code: 'NL', uri: '37i9dQZEVXbK4BFAukDzj3' },
  { country_code: 'PL', uri: '37i9dQZEVXbMZ5PAcNTDXd' },
  { country_code: 'BE', uri: '37i9dQZEVXbND4ZYa46PaA' },
  { country_code: 'AT', uri: '37i9dQZEVXbM1EaZ0igDlz' },
  { country_code: 'IE', uri: '37i9dQZEVXbJIvhIOxXxdp' },
  { country_code: 'UA', uri: '37i9dQZEVXbNcoJZ65xktI' },
  { country_code: 'DK', uri: '37i9dQZEVXbMw2iUtFR5Eq' },
  { country_code: 'FI', uri: '37i9dQZEVXbJQ9kF73GOT2' },
  { country_code: 'CH', uri: '37i9dQZEVXbKx6qX9uN66j' },
  { country_code: 'RO', uri: '37i9dQZEVXbMeCoUmQDLUW' },
  { country_code: 'SK', uri: '37i9dQZEVXbMwW10JmAnzE' },
  { country_code: 'CZ', uri: '37i9dQZEVXbLKI6MPixefZ' },
  { country_code: 'HU', uri: '37i9dQZEVXbMYsavqzfk6k' },

  // North America
  { country_code: 'US', uri: '37i9dQZEVXbLp5XoPON0wI' },
  { country_code: 'MX', uri: '37i9dQZEVXbKUoIkUXteF6' },
  { country_code: 'CA', uri: '37i9dQZEVXbMda2apknTqH' },

  // South America
  { country_code: 'CO', uri: '37i9dQZEVXbL1Fl8vdBUba' },
  { country_code: 'DO', uri: '37i9dQZEVXbMPoK06pe7d6' },
  { country_code: 'BR', uri: '37i9dQZEVXbKzoK95AbRy9' },
  { country_code: 'AR', uri: '37i9dQZEVXbKPTKrnFPD0G' },
  { country_code: 'CL', uri: '37i9dQZEVXbLJ0paT1JkgZ' },
  { country_code: 'PE', uri: '37i9dQZEVXbMGcjiWgg253' },
  { country_code: 'GT', uri: '37i9dQZEVXbJHSzlHx2ZJU' },
  { country_code: 'EC', uri: '37i9dQZEVXbJPVQvqZqpcM' },
  { country_code: 'PA', uri: '37i9dQZEVXbNSiWnkYnziz' },

  // Oceania
  { country_code: 'AU', uri: '37i9dQZEVXbK4fwx2r07XW' },
  { country_code: 'NZ', uri: '37i9dQZEVXbIWlLQoMVEFp' },
];

const radarPlaylists = [
  { country_code: 'US', uri: '37i9dQZF1DWY0DyDKedRYY' },
  { country_code: 'FR', uri: '37i9dQZF1DWWNlI0CRgWup' },
  { country_code: 'BR', uri: '37i9dQZF1DWTVE8ZCcLQ5Q' },
  { country_code: 'MX', uri: '37i9dQZF1DXbpJNWtkXDpL' },
  { country_code: 'KR', uri: '37i9dQZF1DX9IALXsyt8zk' },
  { country_code: 'CA', uri: '37i9dQZF1DX5WmphwNfZfk' },
  { country_code: 'Africa', uri: '37i9dQZF1DWYc8Z858eGwP' },
  { country_code: 'CO', uri: '37i9dQZF1DXbzFWXFlsp56' },
  { country_code: 'PE', uri: '37i9dQZF1DXbzFWXFlsp56' },
  { country_code: 'VE', uri: '37i9dQZF1DXbzFWXFlsp56' },
  { country_code: 'EC', uri: '37i9dQZF1DXbzFWXFlsp56' },
  { country_code: 'AU', uri: '37i9dQZF1DWYIJ3HxqIxIJ' },
  { country_code: 'NZ', uri: '37i9dQZF1DWYIJ3HxqIxIJ' },
  { country_code: 'BE', uri: '37i9dQZF1DXaxwXKCsImRe' },
  { country_code: 'NL', uri: '37i9dQZF1DXaxwXKCsImRe' },
  { country_code: 'LU', uri: '37i9dQZF1DXaxwXKCsImRe' },
  { country_code: 'JP', uri: '37i9dQZF1DX4OR8pnFkwhR' },
  { country_code: 'IN', uri: '37i9dQZF1DWTAtTdFMiJYK' },
  { country_code: 'AR', uri: '37i9dQZF1DX6nghHfwjiMg' },
  { country_code: 'CL', uri: '37i9dQZF1DX6nghHfwjiMg' },
  { country_code: 'UY', uri: '37i9dQZF1DX6nghHfwjiMg' },
  { country_code: 'DE', uri: '37i9dQZF1DX3Vl51vsat7a' },
  { country_code: 'CH', uri: '37i9dQZF1DX3Vl51vsat7a' },
  { country_code: 'AT', uri: '37i9dQZF1DX3Vl51vsat7a' },
  { country_code: 'PH', uri: '37i9dQZF1DWVp4cWdnm5ws' },
  { country_code: 'ID', uri: '37i9dQZF1DWYxUz0Ouugmb' },
  { country_code: 'ES', uri: '37i9dQZF1DX2KWq7Xwva8j' },
];

export { weeklyPlaylists, radarPlaylists };
